#application: monprojet-test-160017
#application: bigdataapp-160115
runtime: php55
api_version: 1
 
handlers:
- url: /.*
  script: index.php
  
- url: /assets
  static_dir: assets
  # Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  
#- url: /
 #  static_files: www/index.html
  # upload: www/index.html

#- url: /(.*)
 #  static_files: www/\1
  # upload: www/(.*)
